# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: mr_robot #minimal
day_night: true
font: rose
font_size: S

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: The research group of Dr. Justin Dressel.
twitter: ''

# Contact (edit or remove options as required)

email: dressel@chapman.edu
phone: 714 516 5949
address:
  street: One University Drive
  city: Orange
  region: CA
  postcode: '92866'
  country: United States
  country_code: US
coordinates:
  latitude: '33.794216'
  longitude: '-117.850348'
directions: Enter the Keck Center building and take the stairs to Office 353 on Floor 3
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
#appointment_url: 'https://calendly.com'
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: false
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
math: true
diagram: true
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
i_am_a_sponsor: true
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
